"""Backend API — FastAPI application.

Endpoints:
  GET  /healthz | /livez      liveness (process up)
  GET  /readyz                readiness (manifest-only KB status — cheap)
  GET  /metrics               Prometheus exposition
  POST /api/v1/assessments    run an assessment on an uploaded snapshot
  GET  /api/v1/assessments    recent assessment summaries
  GET  /api/v1/assessments/{id}        full report JSON
  GET  /api/v1/assessments/{id}/html   rendered HTML report
  GET  /api/v1/assessments/{id}/markdown  markdown report
  GET  /                      web UI (bundled as package data)

Assessments run synchronously in FastAPI's worker threadpool. Recent reports
are cached in a bounded in-memory map; retrieval falls back to the JSON
artifacts persisted in the reports directory, so reports survive restarts
and (with a shared volume) are visible across replicas.
"""

from __future__ import annotations

import re
import threading
import time
from collections import OrderedDict
from importlib import resources

from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse
from pydantic import ValidationError

from .. import __version__
from ..config import Settings, get_settings
from ..errors import AdvisorError, ConfigurationError
from ..knowledge.store import read_manifest
from ..models import AssessmentReport
from ..observability import configure_logging, get_logger, metrics
from ..reporting import render_html, render_markdown, save_reports
from ..service import assess
from .schemas import AssessmentSummary, AssessRequest, HealthResponse

log = get_logger(__name__)

_MAX_STORED = 50
# Report ids are generated by the pipeline; anything else in the URL is
# rejected before it can touch the filesystem.
_REPORT_ID_RE = re.compile(r"^assess-\d{8}-\d{6}-[0-9a-f]{6}$")


def _load_frontend() -> str | None:
    try:
        return (
            resources.files("k8s_upgrade_advisor")
            .joinpath("frontend/index.html")
            .read_text("utf-8")
        )
    except (FileNotFoundError, ModuleNotFoundError):
        return None


class _ReportStore:
    """Bounded, thread-safe, newest-last cache of recent reports. Disk
    (reports_dir JSON artifacts) is the durable tier — see ``get``."""

    def __init__(self, settings: Settings, limit: int = _MAX_STORED) -> None:
        self._reports: OrderedDict[str, AssessmentReport] = OrderedDict()
        self._lock = threading.Lock()
        self._limit = limit
        self._settings = settings

    def add(self, report: AssessmentReport) -> None:
        with self._lock:
            self._reports[report.id] = report
            while len(self._reports) > self._limit:
                self._reports.popitem(last=False)

    def get(self, report_id: str) -> AssessmentReport | None:
        with self._lock:
            report = self._reports.get(report_id)
        if report is not None:
            return report
        if not _REPORT_ID_RE.match(report_id):
            return None
        path = self._settings.paths.reports_dir / f"{report_id}.json"
        if not path.is_file():
            return None
        try:
            report = AssessmentReport.model_validate_json(path.read_text(encoding="utf-8"))
        except (ValidationError, UnicodeDecodeError) as exc:
            log.warning("report_artifact_unreadable", id=report_id, error=str(exc)[:200])
            return None
        self.add(report)
        return report

    def list(self) -> list[AssessmentReport]:
        with self._lock:
            return list(reversed(self._reports.values()))


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()
    configure_logging(settings.observability.log_level, settings.observability.log_json)
    metrics.build_info.labels(version=__version__).set(1)

    app = FastAPI(
        title="k8s-upgrade-advisor",
        version=__version__,
        description="AI Kubernetes upgrade intelligence platform",
    )
    store = _ReportStore(settings)
    frontend_html = _load_frontend()

    if settings.observability.otel_enabled:
        _try_enable_otel(app, settings)

    # ── Middleware: request size guard + observability ───────────────────
    @app.middleware("http")
    async def observe(request: Request, call_next):
        if request.method == "POST":
            length = request.headers.get("content-length")
            if length and length.isdigit() and int(length) > settings.server.max_snapshot_bytes:
                return JSONResponse(
                    status_code=413,
                    content={
                        "detail": f"request body {length} bytes exceeds limit "
                        f"{settings.server.max_snapshot_bytes} "
                        "(K8S_ADVISOR_SERVER__MAX_SNAPSHOT_BYTES)"
                    },
                )
        started = time.monotonic()
        response = await call_next(request)
        route = request.scope.get("route")
        path = getattr(route, "path", request.url.path)
        elapsed = time.monotonic() - started
        metrics.http_requests_total.labels(
            method=request.method, path=path, status=str(response.status_code)
        ).inc()
        metrics.http_request_seconds.labels(method=request.method, path=path).observe(elapsed)
        if settings.server.request_log and not path.startswith(("/healthz", "/livez", "/metrics")):
            log.info(
                "http_request",
                method=request.method,
                path=path,
                status=response.status_code,
                ms=int(elapsed * 1000),
            )
        return response

    # ── Health ───────────────────────────────────────────────────────────
    @app.get("/healthz", response_model=HealthResponse)
    @app.get("/livez", response_model=HealthResponse, include_in_schema=False)
    def healthz() -> HealthResponse:
        return HealthResponse(status="ok", version=__version__)

    @app.get("/readyz", response_model=HealthResponse)
    def readyz() -> HealthResponse:
        # Manifest-only: readiness must never deserialize the corpus.
        kb_loaded, kb_chunks, kb_age = False, 0, None
        manifest = read_manifest(settings.paths.kb_dir)
        if manifest is not None:
            kb_loaded, kb_chunks = True, manifest.chunk_count
            kb_age = round(manifest.age_days, 1)
        return HealthResponse(
            status="ok",
            version=__version__,
            kb_loaded=kb_loaded,
            kb_chunks=kb_chunks,
            kb_age_days=kb_age,
        )

    @app.get("/metrics")
    def prometheus_metrics() -> Response:
        return Response(metrics.render(), media_type="text/plain; version=0.0.4")

    # ── Assessments ──────────────────────────────────────────────────────
    @app.post("/api/v1/assessments", response_model=AssessmentReport)
    def create_assessment(request: AssessRequest) -> AssessmentReport:
        try:
            report = assess(
                request.snapshot,
                request.source_version,
                request.target_version,
                settings,
                dry_run=request.dry_run,
            )
        except ConfigurationError as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        except AdvisorError as exc:
            raise HTTPException(status_code=503, detail=str(exc)) from exc
        store.add(report)
        save_reports(report, settings.paths.reports_dir)
        return report

    @app.get("/api/v1/assessments", response_model=list[AssessmentSummary])
    def list_assessments() -> list[AssessmentSummary]:
        return [
            AssessmentSummary(
                id=r.id,
                created_at=r.created_at.isoformat(),
                source_version=r.source_version,
                target_version=r.target_version,
                verdict=r.readiness.verdict,
                readiness=r.readiness.score,
                confidence=r.readiness.confidence,
                findings=len(r.findings),
                blocking=len(r.blocking_findings),
            )
            for r in store.list()
        ]

    @app.get("/api/v1/assessments/{report_id}", response_model=AssessmentReport)
    def get_assessment(report_id: str) -> AssessmentReport:
        return _must_get(store, report_id)

    @app.get("/api/v1/assessments/{report_id}/html", response_class=HTMLResponse)
    def get_assessment_html(report_id: str) -> HTMLResponse:
        return HTMLResponse(render_html(_must_get(store, report_id)))

    @app.get("/api/v1/assessments/{report_id}/markdown", response_class=PlainTextResponse)
    def get_assessment_markdown(report_id: str) -> PlainTextResponse:
        return PlainTextResponse(render_markdown(_must_get(store, report_id)))

    # ── Frontend ─────────────────────────────────────────────────────────
    @app.get("/", include_in_schema=False)
    def index() -> HTMLResponse:
        if frontend_html is None:
            raise HTTPException(status_code=404, detail="frontend not bundled")
        return HTMLResponse(frontend_html)

    return app


def _must_get(store: _ReportStore, report_id: str) -> AssessmentReport:
    report = store.get(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail=f"assessment {report_id} not found")
    return report


def _try_enable_otel(app: FastAPI, settings: Settings) -> None:
    try:
        from opentelemetry import trace
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor

        provider = TracerProvider(resource=Resource.create({"service.name": "k8s-upgrade-advisor"}))
        exporter = OTLPSpanExporter(endpoint=settings.observability.otel_endpoint)
        provider.add_span_processor(BatchSpanProcessor(exporter))
        trace.set_tracer_provider(provider)
        FastAPIInstrumentor.instrument_app(app, tracer_provider=provider)
        log.info("otel_enabled", endpoint=settings.observability.otel_endpoint)
    except ImportError:
        log.warning(
            "otel_unavailable", hint="pip install 'k8s-upgrade-advisor[otel]' to enable tracing"
        )
