"""Backend API — FastAPI application.

Endpoints:
  GET  /healthz | /livez      liveness (process up)
  GET  /readyz                readiness (manifest-only KB status — cheap)
  GET  /metrics               Prometheus exposition
  POST /api/v1/assessments    run an assessment on an uploaded snapshot
  GET  /api/v1/assessments    recent assessment summaries
  GET  /api/v1/assessments/{id}        full report JSON
  GET  /api/v1/assessments/{id}/html   rendered HTML report
  GET  /api/v1/assessments/{id}/markdown  markdown report
  GET  /                      web UI (bundled as package data)

Operational posture (multi-replica ready):
  - The reports directory is the source of truth; the in-memory map is a
    read cache. Listing and retrieval both fall back to disk, so replicas
    sharing a volume are stateless and interchangeable.
  - Load shedding (concurrency semaphore → 503) bounds parallel work;
    token-bucket rate limiting (→ 429) bounds request *rate* and thereby
    LLM spend; the idempotency cache collapses identical re-submissions.
  - Every request gets an X-Request-ID, bound into all structured logs.
"""

from __future__ import annotations

import hashlib
import re
import threading
import time
import uuid
from collections import OrderedDict
from importlib import resources

import structlog
from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse
from pydantic import ValidationError

from .. import __version__
from ..config import Settings, get_settings
from ..errors import AdvisorError, ConfigurationError
from ..knowledge.store import read_manifest
from ..models import AssessmentReport
from ..observability import configure_logging, get_logger, metrics
from ..reporting import render_html, render_markdown, save_reports
from ..service import assess
from .schemas import AssessmentSummary, AssessRequest, HealthResponse

log = get_logger(__name__)

_MAX_STORED = 50
_MAX_IDEMPOTENCY_KEYS = 512
# Report ids are generated by the pipeline; anything else in the URL is
# rejected before it can touch the filesystem.
_REPORT_ID_RE = re.compile(r"^assess-\d{8}-\d{6}-[0-9a-f]{6}$")


def _load_frontend() -> str | None:
    try:
        return (
            resources.files("k8s_upgrade_advisor")
            .joinpath("frontend/index.html")
            .read_text("utf-8")
        )
    except (FileNotFoundError, ModuleNotFoundError):
        return None


class _TokenBucket:
    """Minimal thread-safe token bucket. Capacity = one minute's quota so a
    quiet client can burst, sustained rate is bounded."""

    def __init__(self, per_minute: int, clock=time.monotonic) -> None:
        self.capacity = float(per_minute)
        self.rate = per_minute / 60.0
        self.tokens = float(per_minute)
        self._clock = clock
        self._last = clock()
        self._lock = threading.Lock()

    def try_acquire(self) -> bool:
        with self._lock:
            now = self._clock()
            self.tokens = min(self.capacity, self.tokens + (now - self._last) * self.rate)
            self._last = now
            if self.tokens >= 1.0:
                self.tokens -= 1.0
                return True
            return False


class _IdempotencyCache:
    """(submission hash → report id) with TTL. Collapses identical
    re-submissions so retry storms don't multiply LLM spend. Per-replica by
    design: a miss is never wrong, just un-optimised."""

    def __init__(self, ttl_seconds: int, clock=time.monotonic) -> None:
        self.ttl = ttl_seconds
        self._clock = clock
        self._entries: OrderedDict[str, tuple[str, float]] = OrderedDict()
        self._lock = threading.Lock()

    @staticmethod
    def key_for(request: AssessRequest) -> str:
        material = (
            f"{request.source_version}|{request.target_version}|{request.dry_run}|"
            + request.snapshot.model_dump_json()
        )
        return hashlib.sha256(material.encode()).hexdigest()

    def get(self, key: str) -> str | None:
        if self.ttl <= 0:
            return None
        with self._lock:
            entry = self._entries.get(key)
            if entry is None:
                return None
            report_id, expires = entry
            if self._clock() > expires:
                del self._entries[key]
                return None
            return report_id

    def put(self, key: str, report_id: str) -> None:
        if self.ttl <= 0:
            return
        with self._lock:
            self._entries[key] = (report_id, self._clock() + self.ttl)
            while len(self._entries) > _MAX_IDEMPOTENCY_KEYS:
                self._entries.popitem(last=False)


class _ReportStore:
    """Read-through cache over the reports directory. Disk is the source of
    truth (shared volume in multi-replica deployments); memory is an
    optimisation. Both get() and list() consult disk."""

    def __init__(self, settings: Settings, limit: int = _MAX_STORED) -> None:
        self._reports: OrderedDict[str, AssessmentReport] = OrderedDict()
        self._lock = threading.Lock()
        self._limit = limit
        self._settings = settings

    def add(self, report: AssessmentReport) -> None:
        with self._lock:
            self._reports[report.id] = report
            while len(self._reports) > self._limit:
                self._reports.popitem(last=False)

    def _load_from_disk(self, report_id: str) -> AssessmentReport | None:
        path = self._settings.paths.reports_dir / f"{report_id}.json"
        if not path.is_file():
            return None
        try:
            report = AssessmentReport.model_validate_json(path.read_text(encoding="utf-8"))
        except (ValidationError, UnicodeDecodeError) as exc:
            log.warning("report_artifact_unreadable", id=report_id, error=str(exc)[:200])
            return None
        self.add(report)
        return report

    def get(self, report_id: str) -> AssessmentReport | None:
        with self._lock:
            report = self._reports.get(report_id)
        if report is not None:
            return report
        if not _REPORT_ID_RE.match(report_id):
            return None
        return self._load_from_disk(report_id)

    def list(self) -> list[AssessmentReport]:
        """Newest-first across memory AND disk — with a shared reports
        volume this makes every replica return the same listing regardless
        of which one served the POST."""
        reports_dir = self._settings.paths.reports_dir
        disk_ids: list[str] = []
        if reports_dir.is_dir():
            disk_ids = sorted(
                (p.stem for p in reports_dir.glob("assess-*.json") if _REPORT_ID_RE.match(p.stem)),
                reverse=True,
            )[: self._limit]
        with self._lock:
            known = dict(self._reports)
        merged: dict[str, AssessmentReport | None] = {rid: known.get(rid) for rid in disk_ids}
        for rid, report in known.items():  # memory-only entries (e.g. --no-save flows)
            merged.setdefault(rid, report)
        out: list[AssessmentReport] = []
        for rid in sorted(merged, reverse=True)[: self._limit]:
            report = merged[rid] or self._load_from_disk(rid)
            if report is not None:
                out.append(report)
        return out


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()
    configure_logging(settings.observability.log_level, settings.observability.log_json)
    metrics.build_info.labels(version=__version__).set(1)

    app = FastAPI(
        title="k8s-upgrade-advisor",
        version=__version__,
        description="AI Kubernetes upgrade intelligence platform",
    )
    store = _ReportStore(settings)
    frontend_html = _load_frontend()
    # Load shedding: assessments are minutes-long threadpool work; beyond
    # the configured concurrency the API answers 503 immediately rather than
    # queueing requests until the worker pool starves. Exposed on app.state
    # so tests can saturate it deterministically.
    app.state.assessment_slots = threading.BoundedSemaphore(
        settings.server.max_concurrent_assessments
    )
    app.state.rate_bucket = (
        _TokenBucket(settings.server.rate_limit_per_minute)
        if settings.server.rate_limit_per_minute > 0
        else None
    )
    app.state.idempotency = _IdempotencyCache(settings.server.idempotency_ttl_seconds)

    if settings.observability.otel_enabled:
        _try_enable_otel(app, settings)

    # ── Middleware: request-id + size guard + observability ──────────────
    @app.middleware("http")
    async def observe(request: Request, call_next):
        request_id = request.headers.get("x-request-id") or uuid.uuid4().hex[:16]
        structlog.contextvars.bind_contextvars(request_id=request_id)
        try:
            if request.method == "POST":
                length = request.headers.get("content-length")
                if length and length.isdigit() and int(length) > settings.server.max_snapshot_bytes:
                    return JSONResponse(
                        status_code=413,
                        content={
                            "detail": f"request body {length} bytes exceeds limit "
                            f"{settings.server.max_snapshot_bytes} "
                            "(K8S_ADVISOR_SERVER__MAX_SNAPSHOT_BYTES)"
                        },
                        headers={"X-Request-ID": request_id},
                    )
            started = time.monotonic()
            response = await call_next(request)
            response.headers["X-Request-ID"] = request_id
            route = request.scope.get("route")
            path = getattr(route, "path", request.url.path)
            elapsed = time.monotonic() - started
            metrics.http_requests_total.labels(
                method=request.method, path=path, status=str(response.status_code)
            ).inc()
            metrics.http_request_seconds.labels(method=request.method, path=path).observe(elapsed)
            if settings.server.request_log and not path.startswith(
                ("/healthz", "/livez", "/metrics")
            ):
                log.info(
                    "http_request",
                    method=request.method,
                    path=path,
                    status=response.status_code,
                    ms=int(elapsed * 1000),
                )
            return response
        finally:
            structlog.contextvars.unbind_contextvars("request_id")

    # ── Health ───────────────────────────────────────────────────────────
    @app.get("/healthz", response_model=HealthResponse)
    @app.get("/livez", response_model=HealthResponse, include_in_schema=False)
    def healthz() -> HealthResponse:
        return HealthResponse(status="ok", version=__version__)

    @app.get("/readyz", response_model=HealthResponse)
    def readyz() -> HealthResponse:
        # Manifest-only: readiness must never deserialize the corpus.
        kb_loaded, kb_chunks, kb_age = False, 0, None
        manifest = read_manifest(settings.paths.kb_dir)
        if manifest is not None:
            kb_loaded, kb_chunks = True, manifest.chunk_count
            kb_age = round(manifest.age_days, 1)
        return HealthResponse(
            status="ok",
            version=__version__,
            kb_loaded=kb_loaded,
            kb_chunks=kb_chunks,
            kb_age_days=kb_age,
        )

    @app.get("/metrics")
    def prometheus_metrics() -> Response:
        return Response(metrics.render(), media_type="text/plain; version=0.0.4")

    # ── Assessments ──────────────────────────────────────────────────────
    @app.post("/api/v1/assessments", response_model=AssessmentReport)
    def create_assessment(request: AssessRequest) -> AssessmentReport:
        # 1. Idempotency: identical submission inside the TTL → cached report.
        idem_key = app.state.idempotency.key_for(request)
        cached_id = app.state.idempotency.get(idem_key)
        if cached_id is not None:
            cached = store.get(cached_id)
            if cached is not None:
                metrics.assessment_cache_total.labels(result="hit").inc()
                log.info("assessment_cache_hit", report_id=cached_id)
                return cached
        metrics.assessment_cache_total.labels(result="miss").inc()

        # 2. Rate limit: bounds request rate (and LLM spend) across time.
        if app.state.rate_bucket is not None and not app.state.rate_bucket.try_acquire():
            raise HTTPException(
                status_code=429,
                detail=f"rate limit exceeded "
                f"({settings.server.rate_limit_per_minute} assessments/minute)",
                headers={"Retry-After": "10"},
            )

        # 3. Load shedding: bounds parallel work right now.
        if not app.state.assessment_slots.acquire(blocking=False):
            raise HTTPException(
                status_code=503,
                detail=f"assessment capacity saturated "
                f"({settings.server.max_concurrent_assessments} in flight); retry shortly",
                headers={"Retry-After": "30"},
            )
        try:
            report = assess(
                request.snapshot,
                request.source_version,
                request.target_version,
                settings,
                dry_run=request.dry_run,
            )
        except ConfigurationError as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        except AdvisorError as exc:
            raise HTTPException(status_code=503, detail=str(exc)) from exc
        finally:
            app.state.assessment_slots.release()
        store.add(report)
        save_reports(report, settings.paths.reports_dir, keep=settings.paths.reports_keep)
        app.state.idempotency.put(idem_key, report.id)
        return report

    @app.get("/api/v1/assessments", response_model=list[AssessmentSummary])
    def list_assessments() -> list[AssessmentSummary]:
        return [
            AssessmentSummary(
                id=r.id,
                created_at=r.created_at.isoformat(),
                source_version=r.source_version,
                target_version=r.target_version,
                verdict=r.readiness.verdict,
                readiness=r.readiness.score,
                confidence=r.readiness.confidence,
                findings=len(r.findings),
                blocking=len(r.blocking_findings),
            )
            for r in store.list()
        ]

    @app.get("/api/v1/assessments/{report_id}", response_model=AssessmentReport)
    def get_assessment(report_id: str) -> AssessmentReport:
        return _must_get(store, report_id)

    @app.get("/api/v1/assessments/{report_id}/html", response_class=HTMLResponse)
    def get_assessment_html(report_id: str) -> HTMLResponse:
        return HTMLResponse(render_html(_must_get(store, report_id)))

    @app.get("/api/v1/assessments/{report_id}/markdown", response_class=PlainTextResponse)
    def get_assessment_markdown(report_id: str) -> PlainTextResponse:
        return PlainTextResponse(render_markdown(_must_get(store, report_id)))

    # ── Frontend ─────────────────────────────────────────────────────────
    @app.get("/", include_in_schema=False)
    def index() -> HTMLResponse:
        if frontend_html is None:
            raise HTTPException(status_code=404, detail="frontend not bundled")
        return HTMLResponse(frontend_html)

    return app


def _must_get(store: _ReportStore, report_id: str) -> AssessmentReport:
    report = store.get(report_id)
    if report is None:
        raise HTTPException(status_code=404, detail=f"assessment {report_id} not found")
    return report


def _try_enable_otel(app: FastAPI, settings: Settings) -> None:
    try:
        from opentelemetry import trace
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor

        provider = TracerProvider(resource=Resource.create({"service.name": "k8s-upgrade-advisor"}))
        exporter = OTLPSpanExporter(endpoint=settings.observability.otel_endpoint)
        provider.add_span_processor(BatchSpanProcessor(exporter))
        trace.set_tracer_provider(provider)
        FastAPIInstrumentor.instrument_app(app, tracer_provider=provider)
        log.info("otel_enabled", endpoint=settings.observability.otel_endpoint)
    except ImportError:
        log.warning(
            "otel_unavailable", hint="pip install 'k8s-upgrade-advisor[otel]' to enable tracing"
        )
